version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - APP_ENV=prod
      - OPENAI_KEY=${OPENAI_KEY}
      - TELEGRAM_BOT_KEY=${TELEGRAM_BOT_KEY}
